[package]
name = "slamjam-homerun-v1"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "slamjam_homerun_v1"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
testing = []
production = []

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }