[features]
seeds = false
skip-lint = false
[programs.localnet]
slamjam_homerun_v1 = "7rxVoKkHEj63EVcKi4gC3utmgs1D4chGP7HzQneMuyKV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
